config/routes.rb
IsbnDB::Application.routes.draw do
  resources :sells

  resources :purchases

  resources :genres

  resources :additional_infos

  resources :books do
    collection do
      get :search
    end
  end

  resources :cities

  resources :countries

  resources :authorships

  resources :people do
    collection do
      get :search
    end
  end

  match 'search/books' => 'search#books', :as => 'book_search', :via => 'post'
  match 'search/authors' => 'search#authors', :as => 'author_search', :via => 'post'

  match '/rankings/mais-vendidos' => 'rankings#_mais_vendidos', :as => 'ranking_mais_vendidos', :via => 'get'

  root :to => 'application#inicio'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    @years_for_select = "<option selected=\"selected\"></option>"
    1900.upto(2012) {|i| @years_for_select += "<option>#{i}</option>"}
    @genres = Genre.order('name').all
  end

  def books
    @results = Book.search params[:book]
    @result_type = 'book'
    render 'results'
  end

  def authors
    @results = Person.search params[:person]
    @result_type = 'person'
    render 'results'
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_person_search_form.html.erb
<%= form_tag(author_search_path) do -%>

  <p>
    <%= label_tag 'Nome' %><br />
    <%= text_field_tag 'person[name]' %>
  </p>

  <p>
    <%= label_tag 'Cidade' %><br />
    <%= text_field_tag 'person[city]' %>
  </p>

  <p>
    <%= label_tag 'País' %><br />
    <%= text_field_tag 'person[country]' %>
  </p>

  <p>
    <%= label_tag 'Nome de Livro que Participou' %><br />
    <%= text_field_tag 'person[book]' %>
  </p>

  <p>
    <%= submit_tag 'Search!' %>
  </p>
<% end -%>

app/views/search/books.html.erb
<%#= render :partial => 'book_search_form' %>

app/views/search/index.html.erb
conteudo aki

app/views/search/results.html.erb
<h1 class="titulos"> Resultados </h1>



<% if @results %>

  <% if @result_type == 'book' %>
    <table width="820px">
    <% @results.each do |result| %>
      <tr class="<%=cycle('even', 'odd')%>">
      <td><%= link_to result.titulo[0..70], book_path(result.id), :class => 'lista'%></td> <td><%= result.authors.first.nil? ? 'Não Cadastrado' : result.authors.first.name[0..20] %></td> <td>R$ <%= result.price %>0</td>
      </tr>
    <% end %>

    </table>

  <% else %>
    <table width="860px">
    <% @results.each do |result| %>
      <tr class="<%=cycle('even', 'odd')%>">
      <td><%= link_to result.name, person_path(result.id), :class => 'lista' %></td>
      <td><%= result.books.first.nil? ? 'Não Cadastrado' : result.books.map {|resultado| resultado.titulo}  %></td>
      </tr>
    <% end %>
    </table>
  <% end %>

<% end %>