config/routes.rb
IsbnDB::Application.routes.draw do
  resources :sells

  resources :purchases

  resources :genres

  resources :additional_infos

  resources :books do
    collection do
      get :search
    end
  end

  resources :cities

  resources :countries

  resources :authorships

  resources :people do
    collection do
      get :search
    end
  end

  match 'search/books' => 'search#books', :as => 'book_search', :via => 'post'
  match 'search/authors' => 'search#authors', :as => 'author_search', :via => 'post'

  match '/rankings/mais-vendidos' => 'rankings#_mais_vendidos', :as => 'ranking_mais_vendidos', :via => 'get'

  root :to => 'application#inicio'

end

app/models/sell.rb
class Sell < ActiveRecord::Base
end

app/controllers/sells_controller.rb
class SellsController < ApplicationController
  # GET /sells
  # GET /sells.json
  def index
    @sells = Sell.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sells }
    end
  end

  # GET /sells/1
  # GET /sells/1.json
  def show
    @sell = Sell.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sell }
    end
  end

  # GET /sells/new
  # GET /sells/new.json
  def new
    @sell = Sell.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sell }
    end
  end

  # GET /sells/1/edit
  def edit
    @sell = Sell.find(params[:id])
  end

  # POST /sells
  # POST /sells.json
  def create
    @sell = Sell.new(params[:sell])

    respond_to do |format|
      if @sell.save
        format.html { redirect_to @sell, notice: 'Sell was successfully created.' }
        format.json { render json: @sell, status: :created, location: @sell }
      else
        format.html { render action: "new" }
        format.json { render json: @sell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sells/1
  # PUT /sells/1.json
  def update
    @sell = Sell.find(params[:id])

    respond_to do |format|
      if @sell.update_attributes(params[:sell])
        format.html { redirect_to @sell, notice: 'Sell was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @sell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sells/1
  # DELETE /sells/1.json
  def destroy
    @sell = Sell.find(params[:id])
    @sell.destroy

    respond_to do |format|
      format.html { redirect_to sells_url }
      format.json { head :ok }
    end
  end
end

app/helpers/sells_helper.rb
module SellsHelper
end

app/views/sells/_form.html.erb
<%= form_for(@sell) do |f| %>
  <% if @sell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sell.errors.count, "error") %> prohibited this sell from being saved:</h2>

      <ul>
      <% @sell.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book_id %><br />
    <%= f.number_field :book_id %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sells/edit.html.erb
<h1>Editing sell</h1>

<%= render 'form' %>

<%= link_to 'Show', @sell %> |
<%= link_to 'Back', sells_path %>

app/views/sells/index.html.erb
<h1>Listing sells</h1>

<table>
  <tr>
    <th>Book</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sells.each do |sell| %>
  <tr>
    <td><%= sell.book_id %></td>
    <td><%= sell.price %></td>
    <td><%= link_to 'Show', sell %></td>
    <td><%= link_to 'Edit', edit_sell_path(sell) %></td>
    <td><%= link_to 'Destroy', sell, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sell', new_sell_path %>

app/views/sells/new.html.erb
<h1>New sell</h1>

<%= render 'form' %>

<%= link_to 'Back', sells_path %>

app/views/sells/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Book:</b>
  <%= @sell.book_id %>
</p>

<p>
  <b>Price:</b>
  <%= @sell.price %>
</p>


<%= link_to 'Edit', edit_sell_path(@sell) %> |
<%= link_to 'Back', sells_path %>